name: or_calculator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  # my packages
  webview_flutter: ^3.0.4
  flutter_tex: ^4.0.3+4
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  # stock packages
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# add splash screen
flutter_native_splash:
  color: "#EFEEE9"
  image: assets/splash.png
  android: true
  ios: true

# add app icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"



flutter:
  uses-material-design: true
# my assets folder
  assets:
    - assets/background_image.png
  fonts:
      # headline
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
      # body
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
      # result
    - family: Poppins-Regular.ttf
      fonts:
        - asset: assets/Poppins-Regular.ttf
